@startuml

start
    while (keep_following)
        if (На линии в пределах \n первых двух датчиков) then (Да)
            :Корректировка движения;
        elseif (На линии, выходя за пределы \n первых датчиков) then (Да)
            :Остановка;
            :Определение угла;
            :Корректировка на угол;
        elseif (Вне линии) then (Да)
            :Вернуться на линию;
            if (Удалось вернуться?) then (Да)
                else (Нет)
                    Stop
            endif
        else (Нет)
        endif
    endwhile
stop

@enduml
