@startuml


state "Инициализация" as Init: -Стоп(вход) \n-Измерение
state "Следование" as Following: -Стоп(вход) \n-Вперед(вход) \n-Измерение \n-Корректировка PID
state "Поворот на 90" as Turn90: -Стоп(вход) \n-Поворот вокруг колеса(вход) \n-Измерение
state "Поиск линии" as FindLine: -Стоп(вход) \n-Вперед(вход) \n-Измерение \n-Корректировка или Стоп(выход)
state "Стоп" as Stop: -Cтоп(вход)

[*] --> Init
Init --> Following: На линии \n
Following --> Following: На линии \n
Following --> Turn90: Прямой угол
Following --> FindLine: Вне линии \n

Turn90 --> Turn90: Не повернули
Turn90 -->Following: На линии \n
Turn90 --> FindLine: Вне линии
FindLine --> Following: На линии
FindLine --> FindLine: Лимит не вышел
Init --> FindLine: Вне линии
Stop <-- FindLine: Вне линии
Stop --> [*]

@enduml

Состояние является атрибутом LineFollower
LineFollower хранит текущее состояние
Состояние это поле или объект?

При активации состояния происходит следующее:
    -Стартовое действие (при активации состояния) - делает само состояние
    -Активация алгоритма (опционально)

Пройти по сценариям и понять какие будут события и какие состояния
    -Начало работы.
        -Состояние: Остановка
            -Положение: На линии
                -Переходим в состояние Следую по линии
                    -Запускаем следование
                    -Активируем PID
        -Состояние: Cледую по линии
            -Положение: На линии
                -Корректировка алгоритмом PID
            -Положение: Прямой угол
                -Переходим в состояние Остановка или Остановка90. Стоп моторы
        -Состояние: Остановка90
            -Переходим в состояние Поворот90
        -Состояние: Поворот90
            -Положение: любое кроме На линии
                -Включаем поворот
            -Положение: на лини (точно на линии)
                -Переходим в состояние Остановка

-Есть состояние
    -Определяет какой алгоритм применять
    -Меняется в зависимости от положения
    -Для разных состояний текущее положение трактуется по-разному
    -Измениться может по инициативе алгоритма
    -Примеры
        -Следую линии
        -Стою
        -Поворот90
-Есть положение относительно линии
    -Вычисляется только на основе измерений датчиков
    -Примеры
        -На линии
        -Прямой угол
        -Вне линии

Необходимо провести изменение если еще не активен ни один алгоритм+
Нужно понять что необходимо выйти из алгоритма
Необходимо производить измерение в цикле каждого алгоритма
Необходимо выбрать алгоритм? Машина состояний?
Необходимо определить позу робота

Получить данные с датчиков
Определить позу
На линии - _(X|)X(X|)_
    Вычислить на основе PID управляющее воздействие
    Применить управляющее воздействие
Прямой угол - _XXXX
    Остановиться
    Включить вращение на месте
Поворот на прямом угле


-Проблема в том, что мы определим позу в виде прямого угла в момент заезда не него.
 В момент поворота мы уже не будем получать на линии или
    -Сделать состояние, которое вычисляется с учетом предыдущего состояния и показаний датчиков
        -Как мы понимаем, что завершили поворот на 90?
            -Мы получили с датчиков ожидаемые промежуточные состояния и вышли на линию
            -Получили с датчиков неожидаемые значения
    -Определять состояние с учетом
-А нужно ли отдельно обрабатывать прямой угол? Или алгоритм с тремя датчиками сам вытянет
-Может быть на прямом угле просто скидывать скорость на ноль на некоторое время?


-Поворачивать лучше не вращением вокруг центра, а вращением вокруг колеса








